version: "3.8"

services:
  web:
    image: python:3.10
    container_name: my_project
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
